sudo: required
services:
  - docker

jobs:
  include:
    - stage: prebuild-test
      sudo: false
      script: bash ./travis/checkx.sh
    - stage: build
      script: docker-compose -f docker-compose-build.yml build
      script: docker-compose -f docker-compose-build.yml up -d && sleep 20s && curl -f localhost:8181 > /dev/null && curl -f localhost:8282 > /dev/null
